/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
if (typeof Promise.withResolvers === "undefined") {
    Promise.withResolvers = function () {
        let resolve, reject;
        const promise = new Promise((res, rej) => { resolve = res; reject = rej; });
        return { promise, resolve, reject };
    };
}

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LumenCatchPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/capture-modal.ts
var import_obsidian = require("obsidian");
var CaptureModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.submitted = false;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    modalEl.addClass("lumen-catch-modal");
    this.textarea = contentEl.createEl("textarea", {
      cls: "lumen-catch-input",
      attr: { placeholder: "\u95EA\u8FC7\u7684\u5FF5\u5934\u2026", rows: "5" }
    });
    window.setTimeout(() => this.textarea.focus(), 0);
    this.textarea.addEventListener("keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        this.submit();
      }
    });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u667A\u80FD\u8BB0\u5F55").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    const text = this.textarea.value.trim();
    if (!text) return;
    this.submitted = true;
    this.close();
    this.onSubmit(text);
  }
  onClose() {
    if (!this.submitted) {
    }
    this.contentEl.empty();
  }
};

// src/util.ts
var ILLEGAL_PATH_CHARS = /* @__PURE__ */ new Set(["\\", "/", ":", "*", "?", '"', "<", ">", "|"]);
function sanitizeSegment(raw) {
  let kept = "";
  for (const ch of raw != null ? raw : "") {
    if (ch.charCodeAt(0) < 32) continue;
    if (ILLEGAL_PATH_CHARS.has(ch)) continue;
    kept += ch;
  }
  return kept.replace(/\s+/g, " ").trim().replace(/^\.+|\.+$/g, "").trim();
}
function pad2(n) {
  return String(n).padStart(2, "0");
}
function fileStamp(at = /* @__PURE__ */ new Date()) {
  return `${at.getFullYear()}${pad2(at.getMonth() + 1)}${pad2(at.getDate())}${pad2(at.getHours())}${pad2(at.getMinutes())}${pad2(at.getSeconds())}`;
}
function localIsoSeconds(at = /* @__PURE__ */ new Date()) {
  return `${at.getFullYear()}-${pad2(at.getMonth() + 1)}-${pad2(at.getDate())}T${pad2(at.getHours())}:${pad2(at.getMinutes())}:${pad2(at.getSeconds())}`;
}
function shortStamp(at = /* @__PURE__ */ new Date()) {
  return `${pad2(at.getHours())}${pad2(at.getMinutes())}${pad2(at.getSeconds())}`;
}
async function ensureFolder(app, path) {
  const parts = path.split("/").filter((p) => p.length > 0);
  let current = "";
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    if (!await app.vault.adapter.exists(current)) {
      await app.vault.createFolder(current);
    }
  }
}

// src/note.ts
function buildQuoteCallout(rawText) {
  const lines = rawText.replace(/\r\n/g, "\n").split("\n");
  const quoted = lines.map((l) => l.length ? `> ${l}` : ">").join("\n");
  return `> [!quote] \u539F\u6587
${quoted}`;
}
function buildInitialNote(rawText, at = /* @__PURE__ */ new Date()) {
  const frontmatter = [
    "---",
    "type: lumen-note",
    "title: ",
    `created: ${localIsoSeconds(at)}`,
    "status: unprocessed",
    "source: lumen-catch",
    "tags:",
    "  - inbox",
    "---",
    ""
  ].join("\n");
  return `${frontmatter}
${buildQuoteCallout(rawText)}
`;
}

// src/ai.ts
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");
var PROVIDER_ENDPOINTS = {
  openrouter: "https://openrouter.ai/api/v1/chat/completions",
  openai: "https://api.openai.com/v1/chat/completions",
  deepseek: "https://api.deepseek.com/v1/chat/completions",
  siliconflow: "https://api.siliconflow.cn/v1/chat/completions"
};
var DEFAULT_SETTINGS = {
  inboxFolder: "Inbox",
  provider: "deepseek",
  apiKey: "",
  model: "deepseek-v4-flash"
};
var LumenCatchSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("\u4FDD\u5B58\u8DEF\u5F84").setDesc("\u6355\u83B7\u7684\u7B14\u8BB0\u843D\u5730\u5230\u8FD9\u4E2A\u6587\u4EF6\u5939\uFF08\u4E0D\u5B58\u5728\u4F1A\u81EA\u52A8\u521B\u5EFA\uFF09\u3002").addText(
      (text) => text.setPlaceholder("Inbox").setValue(this.plugin.settings.inboxFolder).onChange(async (value) => {
        this.plugin.settings.inboxFolder = value.trim() || "Inbox";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("AI \u63D0\u4F9B\u65B9").setDesc("\u7559\u7A7A API Key \u5373\u7EAF\u6355\u83B7\uFF08\u4E0D\u8C03 AI\uFF09\uFF1B\u586B\u4E86\u5C31\u540E\u53F0\u6574\u7406\u3002").addDropdown((dd) => {
      dd.addOption("openrouter", "OpenRouter");
      dd.addOption("openai", "OpenAI");
      dd.addOption("deepseek", "DeepSeek");
      dd.addOption("siliconflow", "\u7845\u57FA\u6D41\u52A8 SiliconFlow");
      dd.setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("API Key").setDesc("\u4E3B\u6A21\u578B\u51ED\u636E\u3002\u7559\u7A7A\u5219\u53EA\u4FDD\u7559\u539F\u6587\uFF0C\u4E0D\u505A AI \u6574\u7406\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u7528\u4FBF\u5B9C\u5FEB\u7684\u6587\u5B57\u6A21\u578B\u5373\u53EF\uFF0C\u4F8B\u5982 deepseek-v4-flash\u3002").addText(
      (text) => text.setPlaceholder("deepseek-v4-flash").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value.trim();
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/ai.ts
var SYSTEM_PROMPT = `\u4F60\u662F\u4E00\u4E2A\u7B14\u8BB0\u6574\u7406\u52A9\u624B\u3002\u7528\u6237\u4F1A\u7ED9\u4F60\u4E00\u6BB5\u968F\u624B\u8BB0\u4E0B\u7684\u3001\u53EF\u80FD\u6F66\u8349\u96F6\u6563\u7684\u5FF5\u5934\u3002
\u8BF7\u5B8C\u6210\u4E24\u4EF6\u4E8B,\u5E76\u53EA\u8FD4\u56DE JSON,\u4E0D\u8981\u4EFB\u4F55\u989D\u5916\u6587\u5B57\u6216\u4EE3\u7801\u56F4\u680F:
1. title: \u4E00\u4E2A\u7B80\u6D01\u3001\u80FD\u6982\u62EC\u8FD9\u6BB5\u5FF5\u5934\u7684\u6807\u9898(\u4E0D\u8D85\u8FC7 20 \u5B57,\u4E0D\u52A0\u4E66\u540D\u53F7/\u5F15\u53F7)
2. body: \u628A\u8FD9\u6BB5\u5FF5\u5934\u6574\u7406\u6210\u901A\u987A\u3001\u6709\u6761\u7406\u7684\u7B14\u8BB0\u6B63\u6587(markdown)\u3002
   \u4FDD\u6301\u539F\u610F,\u4E0D\u8981\u6DFB\u52A0\u539F\u6587\u6CA1\u6709\u7684\u4E8B\u5B9E\u6216\u89C2\u70B9,\u4E0D\u8981\u590D\u8FF0\u7528\u6237\u539F\u8BDD\u3002
\u8FD4\u56DE\u683C\u5F0F: {"title": "...", "body": "..."}`;
function parseAIJson(raw) {
  const tryParse = (s) => {
    try {
      const obj = JSON.parse(s);
      if (obj && typeof obj.title === "string" && typeof obj.body === "string") {
        return { title: obj.title.trim(), body: String(obj.body) };
      }
    } catch (e) {
    }
    return null;
  };
  const direct = tryParse(raw.trim());
  if (direct) return direct;
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced) {
    const stripped = tryParse(fenced[1].trim());
    if (stripped) return stripped;
  }
  throw new Error("AI \u8FD4\u56DE\u975E\u6CD5 JSON");
}
async function callAI(rawText, settings) {
  var _a, _b, _c, _d, _e, _f;
  const endpoint = PROVIDER_ENDPOINTS[settings.provider];
  const payload = {
    model: settings.model,
    temperature: 0.4,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: rawText }
    ]
  };
  const response = await (0, import_obsidian3.requestUrl)({
    url: endpoint,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${settings.apiKey}`
    },
    body: JSON.stringify(payload),
    throw: false
  });
  if (response.status !== 200) {
    throw new Error(`AI \u8BF7\u6C42\u5931\u8D25 (${response.status}): ${(_b = (_a = response.text) == null ? void 0 : _a.slice(0, 200)) != null ? _b : ""}`);
  }
  const content = (_f = (_e = (_d = (_c = response.json) == null ? void 0 : _c.choices) == null ? void 0 : _d[0]) == null ? void 0 : _e.message) == null ? void 0 : _f.content;
  if (typeof content !== "string" || !content.trim()) {
    throw new Error("AI \u8FD4\u56DE\u683C\u5F0F\u5F02\u5E38");
  }
  return parseAIJson(content);
}

// src/main.ts
var LumenCatchPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "capture",
      name: "\u26A1 \u667A\u80FD\u8BB0\u5F55",
      callback: () => this.openCaptureModal()
    });
    this.addRibbonIcon("zap", "\u26A1 \u667A\u80FD\u8BB0\u5F55", () => this.openCaptureModal());
    this.addSettingTab(new LumenCatchSettingTab(this.app, this));
    this.registerObsidianProtocolHandler("lumen-catch", (params) => {
      var _a;
      const text = ((_a = params.text) != null ? _a : "").trim();
      if (text) {
        void this.capture(text);
      } else {
        this.openCaptureModal();
      }
    });
  }
  openCaptureModal(prefill) {
    const modal = new CaptureModal(this.app, (rawText) => this.capture(rawText));
    modal.open();
    if (prefill) {
      window.setTimeout(() => {
        const ta = modal.contentEl.querySelector(".lumen-catch-input");
        if (ta) ta.value = prefill;
      }, 0);
    }
  }
  /** 入口：先同步落地（必成功），再后台触发 AI（即发即忘，不阻塞）。 */
  async capture(rawText) {
    let file;
    try {
      file = await this.captureSync(rawText);
    } catch (e) {
      new import_obsidian4.Notice(`\u6355\u83B7\u5931\u8D25\uFF1A${e instanceof Error ? e.message : String(e)}`);
      this.openCaptureModal(rawText);
      return;
    }
    void this.processAsync(file, rawText);
  }
  // ── 同步段：原文落地 inbox，绝不经过 AI ──────────────────────────────
  async captureSync(rawText) {
    const folder = this.settings.inboxFolder || "Inbox";
    await ensureFolder(this.app, folder);
    const path = (0, import_obsidian4.normalizePath)(`${folder}/catch-${fileStamp()}.md`);
    const file = await this.app.vault.create(path, buildInitialNote(rawText));
    new import_obsidian4.Notice("\u5DF2\u8BB0\u5F55", 1200);
    return file;
  }
  // ── 异步段：AI 回填，失败静默、原文一字不丢 ──────────────────────────
  async processAsync(file, rawText) {
    if (!this.settings.apiKey) return;
    try {
      const { title, body } = await callAI(rawText, this.settings);
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.title = title;
        fm.status = "processed";
      });
      await this.appendBody(file, body);
      await this.tryRename(file, title);
    } catch (e) {
      await this.tagFailure(file);
      console.error("[Lumen Catch] AI processing failed", e);
    }
  }
  /** 在原文引用块下方追加 AI 整理的正文。 */
  async appendBody(file, body) {
    const trimmed = body.trim();
    if (!trimmed) return;
    await this.app.vault.process(file, (data) => `${data.trimEnd()}

${trimmed}
`);
  }
  /** 重命名为 AI 标题；重名追加短后缀；失败静默保留时间戳名。 */
  async tryRename(file, title) {
    var _a;
    const safe = sanitizeSegment(title);
    if (!safe) return;
    const dir = ((_a = file.parent) == null ? void 0 : _a.path) && file.parent.path !== "/" ? `${file.parent.path}/` : "";
    let target = (0, import_obsidian4.normalizePath)(`${dir}${safe}.md`);
    if (this.app.vault.getAbstractFileByPath(target)) {
      target = (0, import_obsidian4.normalizePath)(`${dir}${safe}-${shortStamp()}.md`);
    }
    try {
      await this.app.fileManager.renameFile(file, target);
    } catch (e) {
    }
  }
  /** AI 失败：给笔记打 tag catch-ai-failed，不抛错给用户。 */
  async tagFailure(file) {
    try {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        const tags = Array.isArray(fm.tags) ? fm.tags : fm.tags ? [fm.tags] : [];
        if (!tags.includes("catch-ai-failed")) tags.push("catch-ai-failed");
        fm.tags = tags;
      });
    } catch (e) {
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
